# Generated by Django 5.0.7 on 2024-07-09 17:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tittle', models.CharField(max_length=100, verbose_name='Título')),
                ('director', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('point', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Nota Media')),
            ],
            options={
                'unique_together': {('tittle', 'director')},
            },
        ),
    ]
